"""core schema (doc 02 §4)

Revision ID: 0001
Revises:
Create Date: 2026-07-10

The source of truth for the core schema. DDL is explicit (not autogenerated) so it matches
doc 02 §4 exactly, including the pg_trgm extension and the jsonb_path_ops GIN index.
Later stages add columns/tables via new additive migrations (0002 = doc 13 A-2/A-4).
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # --- Layer 1: immutable observations ---
    op.execute(
        """
        CREATE TABLE raw_events (
          id BIGSERIAL PRIMARY KEY,
          source TEXT NOT NULL,
          source_event_uid TEXT NOT NULL,
          event_type TEXT NOT NULL,
          occurred_at TIMESTAMPTZ NOT NULL,
          ingested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          origin TEXT NOT NULL DEFAULT 'live',
          payload JSONB NOT NULL,
          UNIQUE (source, source_event_uid)
        )
        """
    )
    op.execute("CREATE INDEX ix_raw_events_occurred_at ON raw_events (occurred_at)")
    op.execute(
        "CREATE INDEX ix_raw_events_payload ON raw_events USING gin (payload jsonb_path_ops)"
    )

    # --- Layer 2: durable things ---
    op.execute(
        """
        CREATE TABLE entities (
          id BIGSERIAL PRIMARY KEY,
          entity_type TEXT NOT NULL,
          canonical_name TEXT NOT NULL,
          category TEXT,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          merged_into BIGINT REFERENCES entities(id),
          attrs JSONB NOT NULL DEFAULT '{}'
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_entities_name_trgm ON entities USING gin (canonical_name gin_trgm_ops)"
    )

    op.execute(
        """
        CREATE TABLE entity_links (
          id BIGSERIAL PRIMARY KEY,
          entity_id BIGINT NOT NULL REFERENCES entities(id),
          raw_event_id BIGINT REFERENCES raw_events(id),
          linked_entity_id BIGINT REFERENCES entities(id),
          rule TEXT NOT NULL,
          confidence REAL NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX ix_entity_links_entity_id ON entity_links (entity_id)")

    op.execute(
        """
        CREATE TABLE entity_merge_queue (
          id BIGSERIAL PRIMARY KEY,
          entity_a BIGINT NOT NULL REFERENCES entities(id),
          entity_b BIGINT NOT NULL REFERENCES entities(id),
          confidence REAL NOT NULL,
          evidence JSONB NOT NULL,
          status TEXT NOT NULL DEFAULT 'pending',
          decided_at TIMESTAMPTZ
        )
        """
    )

    op.execute(
        """
        CREATE TABLE themes (
          id BIGSERIAL PRIMARY KEY,
          name TEXT UNIQUE NOT NULL,
          description TEXT
        )
        """
    )
    op.execute(
        """
        CREATE TABLE entity_themes (
          entity_id BIGINT NOT NULL,
          theme_id BIGINT NOT NULL,
          source TEXT,
          PRIMARY KEY (entity_id, theme_id)
        )
        """
    )

    # --- Layers 3–6 outputs ---
    op.execute(
        """
        CREATE TABLE comprehension_cards (
          id BIGSERIAL PRIMARY KEY,
          entity_id BIGINT NOT NULL,
          version INT NOT NULL,
          as_of TIMESTAMPTZ NOT NULL,
          card JSONB NOT NULL,
          model TEXT NOT NULL,
          cost_usd NUMERIC(8,4),
          created_at TIMESTAMPTZ DEFAULT now(),
          UNIQUE (entity_id, version)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE entity_metrics_daily (
          entity_id BIGINT NOT NULL,
          metric TEXT NOT NULL,
          day DATE NOT NULL,
          value NUMERIC NOT NULL,
          PRIMARY KEY (entity_id, metric, day)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE maturity_promotions (
          entity_id BIGINT NOT NULL,
          stage TEXT NOT NULL,
          promoted_at TIMESTAMPTZ NOT NULL,
          evidence_event BIGINT REFERENCES raw_events(id),
          PRIMARY KEY (entity_id, stage)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE momentum_states (
          entity_id BIGINT NOT NULL,
          day DATE NOT NULL,
          state TEXT NOT NULL,
          score NUMERIC,
          inputs JSONB,
          PRIMARY KEY (entity_id, day)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE gate_decisions (
          id BIGSERIAL PRIMARY KEY,
          entity_id BIGINT NOT NULL,
          week DATE NOT NULL,
          decision TEXT NOT NULL,
          score NUMERIC NOT NULL,
          components JSONB NOT NULL,
          created_at TIMESTAMPTZ DEFAULT now()
        )
        """
    )
    op.execute(
        """
        CREATE TABLE impact_briefs (
          id BIGSERIAL PRIMARY KEY,
          entity_id BIGINT NOT NULL,
          version INT NOT NULL,
          as_of TIMESTAMPTZ NOT NULL,
          brief JSONB NOT NULL,
          status TEXT NOT NULL DEFAULT 'draft',
          model TEXT,
          cost_usd NUMERIC(8,4),
          reviewed_at TIMESTAMPTZ,
          created_at TIMESTAMPTZ DEFAULT now()
        )
        """
    )
    op.execute(
        """
        CREATE TABLE brief_scores (
          brief_id BIGINT PRIMARY KEY REFERENCES impact_briefs(id),
          scored_at TIMESTAMPTZ,
          materialized TEXT,
          falsifier_tripped BOOLEAN,
          notes TEXT
        )
        """
    )

    # --- Exposure map (loaded from YAML, doc 08) ---
    op.execute(
        """
        CREATE TABLE exposure_companies (
          ticker TEXT PRIMARY KEY,
          name TEXT,
          sector TEXT,
          doc JSONB NOT NULL,
          loaded_at TIMESTAMPTZ
        )
        """
    )
    op.execute(
        """
        CREATE TABLE reach_links (
          category TEXT NOT NULL,
          ticker TEXT NOT NULL,
          revenue_line TEXT NOT NULL,
          relation TEXT NOT NULL,
          PRIMARY KEY (category, ticker, revenue_line, relation)
        )
        """
    )

    # --- Bookkeeping ---
    op.execute(
        """
        CREATE TABLE collector_runs (
          id BIGSERIAL PRIMARY KEY,
          source TEXT,
          started_at TIMESTAMPTZ,
          finished_at TIMESTAMPTZ,
          ok BOOLEAN,
          events_new INT,
          error TEXT
        )
        """
    )
    op.execute(
        """
        CREATE TABLE pipeline_runs (
          id BIGSERIAL PRIMARY KEY,
          stage TEXT,
          as_of TIMESTAMPTZ,
          started_at TIMESTAMPTZ,
          finished_at TIMESTAMPTZ,
          ok BOOLEAN,
          notes TEXT
        )
        """
    )


def downgrade() -> None:
    for table in [
        "pipeline_runs",
        "collector_runs",
        "reach_links",
        "exposure_companies",
        "brief_scores",
        "impact_briefs",
        "gate_decisions",
        "momentum_states",
        "maturity_promotions",
        "entity_metrics_daily",
        "comprehension_cards",
        "entity_themes",
        "themes",
        "entity_merge_queue",
        "entity_links",
        "entities",
        "raw_events",
    ]:
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
