"""Graph AI explanations — graph_explanations

Revision ID: 0013
Revises: 0012
Create Date: 2026-07-28

One narrated explanation per entity's relationship subgraph ("who are these people, why is
OpenAI in this graph, what does the team pedigree signal"), generated by the LLM configured
under ``graph_explain_provider`` and served instantly by the dashboard's explanation panel.

``subgraph_hash`` fingerprints the exact nodes+edges the text was written about: the daily
``explain-graphs`` step regenerates a row ONLY when the hash changed (new enrichment landed),
so steady-state cost is near zero. One row per entity (UNIQUE), upserted.

Additive only — no existing column dropped or rewritten (invariant 1).
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0013"
down_revision: str | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE graph_explanations (
          id BIGSERIAL PRIMARY KEY,
          entity_id BIGINT NOT NULL REFERENCES entities(id),
          subgraph_hash TEXT NOT NULL,     -- sha256 of the nodes+edges the text describes
          content JSONB NOT NULL,          -- {overview, key_people, organizations, signals} markdown
          model TEXT NOT NULL,
          cost_usd NUMERIC(8,4) NOT NULL DEFAULT 0,
          node_count INT NOT NULL DEFAULT 0,
          edge_count INT NOT NULL DEFAULT 0,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          UNIQUE (entity_id)
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS graph_explanations")
